version: '3.4'

services:
  mssql.data:
    image: microsoft/mssql-server-linux:2017-latest

  mongodb.data:
    image: mongo:4.0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.4
    container_name: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.4

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbitmq



